### ISSUE TITLE
Question: multiple interfaces

### ISSUE THREAD

**Issue by aledbf** [google/seesaw#10]
Is required the use of multiple interfaces? Or it can be the just one or an alias?
Context of this question: I want to provide multiple backends in [keepalived-vip](https://github.com/kubernetes/contrib/tree/master/keepalived-vip) behind a flag so it's possible to choose between keepalived or seesaw

Thanks

**Comment by baptr** [comment]
Seesaw shares a VRRP MAC address between the load balancing interfaces on each node, and only brings up that interface when the node is acting as Master, so it really needs both.

**Comment by aledbf** [comment]
@baptr thanks
