### ISSUE TITLE
error unble to install seesaw

### ISSUE THREAD

**Issue by tehseensagar** [google/seesaw#32]
strange unable to compile it. I've followed following steps accordingly,

downloaded the package into into /home/<my-user>software/seesaw-master

apt-get install golang
apt-get install libnl-3-dev libnl-genl-3-dev
go get -u golang.org/x/crypto/ssh
go get -u github.com/dlintw/goconf
go get -u github.com/golang/glog
go get -u github.com/miekg/dns
go get -u github.com/kylelemons/godebug/pretty
apt-get install protobuf-compiler
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

go env output

GOARCH="amd64"
GOBIN="/usr/bin/go"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/go-1.6"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

cd /home/<my-user>software/seesaw-master

when running " make test " command it give following errors

go build ./...
binaries/seesaw_cli/main.go:31:2: cannot find package "github.com/google/seesaw/cli" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/cli (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/cli (from $GOPATH)
binaries/seesaw_cli/main.go:32:2: cannot find package "github.com/google/seesaw/common/conn" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/common/conn (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/common/conn (from $GOPATH)
binaries/seesaw_cli/main.go:33:2: cannot find package "github.com/google/seesaw/common/ipc" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/common/ipc (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/common/ipc (from $GOPATH)
binaries/seesaw_cli/main.go:34:2: cannot find package "github.com/google/seesaw/common/seesaw" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/common/seesaw (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/common/seesaw (from $GOPATH)
binaries/seesaw_ecu/main.go:24:2: cannot find package "github.com/google/seesaw/common/server" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/common/server (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/common/server (from $GOPATH)
binaries/seesaw_ecu/main.go:25:2: cannot find package "github.com/google/seesaw/ecu" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ecu (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ecu (from $GOPATH)
binaries/seesaw_engine/main.go:30:2: cannot find package "github.com/google/seesaw/engine" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/engine (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/engine (from $GOPATH)
binaries/seesaw_engine/main.go:29:2: cannot find package "github.com/google/seesaw/engine/config" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/engine/config (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/engine/config (from $GOPATH)
binaries/seesaw_ha/main.go:27:2: cannot find package "github.com/google/seesaw/ha" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ha (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ha (from $GOPATH)
binaries/seesaw_healthcheck/main.go:26:2: cannot find package "github.com/google/seesaw/healthcheck" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/healthcheck (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/healthcheck (from $GOPATH)
binaries/seesaw_ncc/main.go:33:2: cannot find package "github.com/google/seesaw/ncc" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ncc (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ncc (from $GOPATH)
binaries/seesaw_watchdog/main.go:27:2: cannot find package "github.com/google/seesaw/watchdog" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/watchdog (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/watchdog (from $GOPATH)
cli/show.go:29:2: cannot find package "github.com/google/seesaw/quagga" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/quagga (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/quagga (from $GOPATH)
common/seesaw/seesaw.go:27:2: cannot find package "github.com/google/seesaw/ipvs" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ipvs (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ipvs (from $GOPATH)
engine/core.go:36:2: cannot find package "github.com/google/seesaw/ncc/client" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ncc/client (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ncc/client (from $GOPATH)
engine/core.go:37:2: cannot find package "github.com/google/seesaw/ncc/types" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/ncc/types (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/ncc/types (from $GOPATH)
engine/config/config.go:32:2: cannot find package "github.com/google/seesaw/pb/config" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/pb/config (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/pb/config (from $GOPATH)
ipvs/ipvs.go:27:2: cannot find package "github.com/google/seesaw/netlink" in any of:
        /usr/lib/go-1.6/src/github.com/google/seesaw/netlink (from $GOROOT)
        /usr/share/go-1.6/src/github.com/google/seesaw/netlink (from $GOPATH)
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

Any idear what's wrong looking forward for your kind response.

Regards
Tehseen

**Comment by tiepnv-viosoft** [comment]
Hi tehseensagar ,
I'm planning to build seesaw on ubuntu 16.04 LTS but I had an error as below:
```
go get -u github.com/miekg/dns
package context: unrecognized import path "context" (import path does not begin with hostname)
```
After searching google, I installed golang-1.10 and passed the error. However, I encountered the same error as yours.
Could you show me how to fix that error?

Thanks,
TiepNV
