### ISSUE TITLE
Using go based netlink instead of libnl

### ISSUE THREAD

**Issue by dhilipkumars** [google/seesaw#34]
Hi All,

Is there a plan to use a go based netlink library instead of libnl in the future? Or Has it been considered already?  This is a go based [netlink ](https://github.com/vishvananda/netlink) implementation but im not sure if it already supports VS based messages yet.  

We are planning to use seesaw for a larger project like kubernetes to support IPVS and it would be great to know its roadmap. 

CC: @baptr

Thanks in Advance,
Dhilip

**Comment by baptr** [comment]
Not currently planned. The cgo wrapper is working well enough for the relatively small netlink interaction we need at this point, though replacing some of the ncc ip funcs would be nice eventually.

Is there some particular additional functionality you're looking for?

**Comment by dhilipkumars** [comment]
yes we are using seesaw for a feature which is planned to be merged with kubernetes,  vendoring seesaw would be very convenient if it did not depend on a c library, and our contribution will be more readily accepted. 

The link i mentioned before is a generic netlink library, which is used by several projects.  [This one](https://github.com/google/cadvisor/tree/master/utils/cpuload/netlink) is implemented by cadvisor team which also uses a very tiny subset of netlink messages. 

If we decide to stick with seesaw would you be interested in a PR for this?

**Comment by opsnull** [comment]
@dhilipkumars I'm interested in the planned k8s feature using seesaw, Could you tell me something about it?

**Comment by dhilipkumars** [comment]
Hi we are using docker's libnetwork please see the PR in review https://github.com/kubernetes/kubernetes/pull/46580
