### ISSUE TITLE
Question on seesaw

### ISSUE THREAD

**Issue by johntwei** [google/seesaw#35]
Hello,
I was reading code and documentation on seesaw and have few questions.
#1. In README.md, it said --- "Direct Server Return (DSR)" is used. To my knowledge, DSR means the backend server send response to the original server who sent request to VIP. But, I saw the code in "ncc/iptables.go" ---
          // Rewrite source address for NAT'd packets so backend reply traffic comes
         // back to the load balancer.
        natPostrouting := "POSTROUTING -t nat -m ipvs -p {{.Proto}}{{with .Port}} --vport {{.}}{{end}} " +
                "--vaddr {{.ServiceVIP}} -j SNAT --to-source {{.ClusterVIP}} --random"
Can someone clarify if seesaw backend server response to original server or to load balancer node?

#2 In README.rd, it said -- "Seesaw v2 is a Linux Virtual Server (LVS) based load balancing platform."
 How LVS is used by seesaw? I noticed that ip_vs module is needed. But, seesaw is not using ipvsadm CLI.

Thanks for the help.
John

**Comment by 4a6f656c** [comment]
Re (1) - Seesaw is capable of both DSR and NAT, depending on configuration (see https://github.com/google/seesaw/blob/master/pb/config/config.proto#L139). In DSR mode the replies will be delivered from the load balancer to the backend, then returned directly from the backend to the client.

Re (2) - Seesaw controls IPVS directly via netlink - see https://github.com/google/seesaw/blob/master/ipvs/ipvs.go and  https://github.com/google/seesaw/tree/master/netlink.

**Comment by johntwei** [comment]
Re (1) - Thanks for the info that Seesaw can support either NAT or DSR. For DSR mode, can I assume that we also need to configure backend real server to deal with the ARP issue (e.g configuring VIP on loopback, and hide loopback)?

New question #3: One VIP can run on just one of the two seesaw server (master/slave), is this correct? I saw a Google Maglev paper, "N+1" redundancy was mentioned in the paper. It seems that, with Maglev, same VIP an be served by multiple Maglev load balancer.

John
