### ISSUE TITLE
Unable to start SeeSaw

### ISSUE THREAD

**Issue by ralphdt** [google/seesaw#41]
I have SeeSaw compiled and installed on Centos 7. The Watchdog service starts and kicks off the other 5 components but the Engine fails to start (see log below).

The log file doesn't really give me any clues as to what its not happy about. Any pointers on where I should be looking ?

[root@seesaw-1 bin]# ./seesaw_engine
F0306 19:55:43.201250   60397 core.go:250] Failed to connect to NCC: Failed to establish connection: dial unix /var/run/seesaw/nc            c/ncc.sock: connect: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc420117500, 0xc4201d2000, 0xb0, 0x1c6)

[root@seesaw-1 seesaw]# more seesaw_engine.INFO
Log file created at: 2018/03/06 19:46:52
Running on machine: seesaw-1
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0306 19:46:52.217240   60124 core.go:121] Seesaw Engine starting for seesaw
F0306 19:46:53.724640   60124 core.go:250] Failed to connect to NCC: Failed to establish connection: dial unix /var/run/seesaw/ncc/ncc.sock: connect: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42000e001, 0xc4202ce000, 0x3ba, 0x2710)

**Comment by baptr** [comment]
Is the seesaw_ncc running?

Is there anything in seesaw_ncc.INFO that sheds more light?

**Comment by ralphdt** [comment]
"make test" gives this error (although "make install" works and binaries are copied and start): 

ok      seesaw/engine   6.778s
ok      seesaw/engine/config    0.007s
ok      seesaw/ha       0.004s
--- FAIL: TestHTTPChecker (0.00s)
        healthcheck_test.go:161: HTTP healthcheck {GET /, "", 0} to [::1]:45309 failed: Get http://::1/: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /, "", 200} to [::1]:45309 failed: Get http://::1/: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /healthz, "", 0} to [::1]:45309 failed: Get http://::1/healthz: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /healthz, "", 200} to [::1]:45309 failed: Get http://::1/healthz: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /healthz, "ok\n", 200} to [::1]:45309 failed: Get http://::1/healthz: invalid URL port       ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /notfound, "", 0} to [::1]:45309 failed: Get http://::1/notfound: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {GET /notfound, "", 404} to [::1]:45309 failed: Get http://::1/notfound: invalid URL port ":      1"
        healthcheck_test.go:161: HTTP healthcheck {HEAD /healthz, "", 0} to [::1]:45309 failed: Head http://::1/healthz: invalid URL port ":1"
        healthcheck_test.go:161: HTTP healthcheck {HEAD /healthz, "", 200} to [::1]:45309 failed: Head http://::1/healthz: invalid URL port ":      1"
        healthcheck_test.go:161: HTTP healthcheck {HEAD /notfound, "", 0} to [::1]:45309 failed: Head http://::1/notfound: invalid URL port ":      1"
        healthcheck_test.go:161: HTTP healthcheck {HEAD /notfound, "", 404} to [::1]:45309 failed: Head http://::1/notfound: invalid URL port       ":1"
2018/03/07 09:11:53 http: TLS handshake error from 127.0.0.1:56904: tls: first record does not look like a TLS handshake
2018/03/07 09:11:53 http: TLS handshake error from [::1]:57968: EOF

**Comment by ralphdt** [comment]
"Is the seesaw_ncc running?
Is there anything in seesaw_ncc.INFO that sheds more light?"

seesaw_ncc is NOT running

/var/log/seesaw

[root@seesaw-1 seesaw]# more seesaw_ncc.ERROR
Log file created at: 2018/03/07 09:13:53
Running on machine: seesaw-1
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0307 09:13:53.299202    3291 ipvs.go:40] IPVS initialisation failed: failed to resolve family name
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc42000e001, 0xc42029c000, 0x377, 0x2710)
        /root/work/src/github.com/golang/glog/glog.go:769 +0xcf

**Comment by ralphdt** [comment]
Is there a HowTo/Troubleshooting guide anyone can point me too?

**Comment by baptr** [comment]
Does your box by chance not have ipv6 support?

**Comment by baptr** [comment]
For the actually ncc failure: is the ip_vs module loaded?

**Comment by baptr** [comment]
https://github.com/google/seesaw/blob/master/doc/getting_started.md may
help.

**Comment by 4a6f656c** [comment]
This:
```shell
F0307 09:13:53.299202 3291 ipvs.go:40] IPVS initialisation failed: failed to resolve family name
```
means that netlink does not know anything about IPVS - the kernel does not have IPVS support, which may mean that the IPVS module has not been loaded. The referenced getting started document details the kernel requirements.
